// <auto-generated />
namespace Next_Super_Hero.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addHotSuper : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addHotSuper));
        
        string IMigrationMetadata.Id
        {
            get { return "201912030357368_addHotSuper"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
